### ISSUE TITLE
Orçamentos Crachás

### ISSUE THREAD

**Issue by leonardo-minora** [devopsday-natal/devopsdays-web#9]

**Comment by jgdsfilho** [comment]
Eu posso ver isso. Só preciso saber o formato (dimensões dos adesivos).

**Comment by jgdsfilho** [comment]
Crachás mais elaborados (tipo acrílico), ou simples mesmo?

**Comment by Igorolivei** [comment]
Simples, num material como o dos crachás do PythonDay, já estaria bom.

**Comment by Igorolivei** [comment]
Movido pra issue #14
